from worlds.oribf.test import OriBlindForestTestBase


class DoubleJumpAndGlideAccessTest(OriBlindForestTestBase):

    def test_double_jump_and_glide_location(self) -> None:
        """Test locations that require Double Jump and Glide"""
        locations = [
            "LeftGrottoTeleporterExp",
            "MistyPostClimbAboveSpikePit",
            "LostGroveHiddenExp",
            "LostGroveAbilityCell",
            "LostGroveTeleporter",
            "GroveAboveSpiderWaterExp",
            "GroveAboveSpiderWaterEnergyCell",
            "UpperGinsoUpperLeftKeystone",
            "UpperGinsoUpperRightKeystone",
            "GinsoEscapeExit",
            "GinsoEscapeHangingExp",
            "GinsoEscapeProjectileExp",
            "GinsoEscapeJumpPadExp",
            "GinsoEscapeSpiderExp",
            "ClimbSkillTree",
            "KuroPerchExp",
            "MistyPlant",
            "MistyMortarCorridorUpperExp",
            "MistyMortarCorridorHiddenExp",
            "MistyPostClimbSpikeCave",
            "MistyAbilityCell",
            "MistyKeystone2",
            "MistyKeystone1",
            "MistyFrogNookExp",
            "MistyKeystone3",
            "MistyGrenade",
            "MistyKeystone4",
            "MistyPostClimbAboveSpikePit",
            "GumonSeal",
            "SorrowLowerLeftKeystone",
            "LeftSorrowKeystone3",
            "LeftSorrowKeystone4",
            "LeftSorrowEnergyCell",
            "UpperSorrowFarLeftKeystone",
            "UpperSorrowSpikeExp",
            "UpperSorrowLeftKeystone",
            "UpperSorrowRightKeystone",
            "UpperSorrowFarRightKeystone",
            "SunstonePlant",
            "Sunstone",
            "HoruR2",
            "SwampTeleporterAbilityCell",
            "InnerSwampEnergyCell",
            "ValleyRightFastStomplessCell",
            "SorrowHealthCell",
            "LeftSorrowAbilityCell",
            "LeftSorrowGrenade",
            "LeftSorrowPlant",
            "LeftSorrowKeystone1",
            "LeftSorrowKeystone2",
            "ChargeJumpSkillTree",

            "LowerGinsoKeystone1",
            "LowerGinsoKeystone2",
            "UpperGinsoLowerKeystone",
            "UpperGinsoRightKeystone",
            "TopGinsoLeftLowerExp",
            "BelowGrottoTeleporterHealthCell",
            "BelowGrottoTeleporterPlant",
            "HoruFieldsEnergyCell",
            "HoruMap",
            "HoruL1",
            "HoruL2",
            "HoruL3",
            "HoruR1HangingExp",
            "HoruR1Mapstone",
            "HoruR1",
            "HoruR2",
            "HoruR3",
            "HoruR1EnergyCell",
            "HoruR3Plant",
            "SorrowEntranceAbilityCell",
            "SorrowSpikeKeystone",
            "SorrowHiddenKeystone",
            "SorrowMainShaftKeystone",
            "SorrowMapstone",
            "SorrowMap"
        ]

        items = [["DoubleJump", "Glide"]]
        self.assertAccessDependency(locations, items)